language: rust
os: linux
dist: bionic
sudo: false
rust:
  - 1.31
  - stable
  - beta
  - nightly
install:
  - cargo fetch --verbose
script:
  - cargo check --verbose
  - cargo test --verbose
branches:
  except:
   - /dependabot\/cargo\/.+/
