language: rust
cache: cargo
os: linux
dist: bionic
rust:
  - 1.37.0
  - stable
  - beta
install:
  - cargo fetch --verbose
script:
  - cargo build --verbose
  - cargo test --verbose
branches:
  except:
   - /dependabot\/cargo\/.+/
git:
  depth: 5
