language: rust
cache: cargo
os: linux
dist: bionic
sudo: false
rust:
  - 1.34.0
  - stable
  - beta
  #- nightly
install:
  - rustup component add rustfmt
  - rustfmt --version
  - rustup component add clippy
  - clippy-driver --version
  - cargo fetch --verbose
script:
  - cargo check --verbose
  - cargo test --verbose
  #- cargo clippy
  - cargo fmt --verbose -- --check --verbose
branches:
  except:
   - /dependabot\/cargo\/.+/
git:
  depth: 5
