[package]
name = "hexbot"
description = "My solution for: https://noopschallenge.com/challenges/hexbot"
version = "0.0.8-dev"
authors = ["rusty-snake <print_hello_world+Public@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
tint = "1.0.1"

[dependencies.reqwest]
version = "0.9"

[dependencies.serde]
version = "1.0"
default_features = false
features = ["derive"]


[features]
# description() on Error types is deprecated, if you still need it add
# `--feature="ErrorDescription"` to the cargo command.
ErrorDescription = []
