[package]
name = "hexbot"
description = "My solution for: https://noopschallenge.com/challenges/hexbot"
version = "0.0.1"
authors = ["rusty-snake <print_hello_world+Public@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
repository = "https://github.com/rusty-snake/hexbot"

[dependencies]
reqwest = "0.9.18"
serde = { version = "1.0", default_features = false, features = ["derive"] }
