[package]
name = "hexbot"
description = "My solution for: https://noopschallenge.com/challenges/hexbot"
version = "0.0.5"
authors = ["rusty-snake <print_hello_world+Public@protonmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"

[dependencies]
reqwest = "0.9.18"
serde = { version = "1.0", default_features = false, features = ["derive"] }
tint = "1.0.1"

[features]
# description() is deprecated; use Display
ErrorDescription = []
