version: 1

update_configs:

  - package_manager: "rust:cargo"
    directory: "/"
    update_schedule: "live"

    default_reviewers:
      - "rusty-snake"

    default_labels:
      - "dependencies"

    # Update all dependencies in Cargo.lock
    allowed_updates:
      - match:
          update_type: "all"

    # Update also Cargo.toml
    version_requirement_updates: "auto"
